# Asterisk Docker container,
# author: Dimitar Kokov,
# version: 0.4,
# date: 2024-08-30

# docker-compose up --build -d

# docker-compose down -v

version: "3"

services:
  banafo-asterisk:
    image: ban-ast-mod-image
    build:
        context: ../
        dockerfile: ./docker/Dockerfile
    network_mode: "host"
    hostname: banafo-ast-mod
    container_name: banafo-ast-mod
    environment:
      - TZ=Europe/Sofia

