# FreeSWITCH + mod_banafo_trancribe Docker container,
# author: Dimitar Kokov,
# version: 0.3,
# date: 2024-08-28

# docker network create ban_mod_network
# docker-compose up --build -d

# docker-compose down -v

version: "3"

services:
  banafo-freeswitch-mod:
    image: banafo-fs-mod-image
    build:
        context: ../
        dockerfile: ./docker/Dockerfile
    network_mode: "host"
    hostname: banafo-fs-mod
    container_name: banafo-fs-mod
    environment:
      - TZ=Europe/Sofia

